version: '3'
volumes:
  jenkins_home:

services:
  app:
    build:
      context: ""
      dockerfile: .docker/Dockerfile
    image: school
    ports:
      - 8080:80
    volumes:
      - .:/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: school
      DB_USERNAME: school_admin
      DB_PASSWORD: 123456
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: school_admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home