<?php
require "/app/app/vendor/autoload.php";
use School\Student;
use School\Helper;
// Create a student entity
//include_once '/Users/kiran.rao/Sites/School_project/src/Student.php';
if (!empty($_POST)) {
    $student = new student();
    $student->name = $_POST['student_name'];
    $student->parent_name = $_POST['parent_name'];
    $student->address = $_POST['address'];
    $student->class_id = $_POST['class_id'];
    $student->section_id = $_POST['section_id'];
    $msg = $student->create('student');

}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Untitled Form</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body">

<img id="top" src="top.png" alt="">
<div id="form_container">

    <h1><a>Create student</a></h1>
    <?php
    if (!empty($msg)) {
        print("<div class='msg'>$msg</div>");
    }
    ?>
    <form id="form_119127" class="appnitro" method="post" action="">
        <div class="form_description">
            <h2>Create student</h2>
            <!--            <p>This is your form description. Click here to edit.</p>-->
        </div>
        <ul>
            <li id="li_2">
                <label class="description" for="element_2">student Name </label>
                <div>
                    <input id="student_name" name="student_name" class="element text medium" type="text" maxlength="255"
                           value=""/>
                </div>
            </li>
            <li id="li_2_1">
                <label class="description" for="parent_name">Parent Name </label>
                <div>
                    <input id="parent_name" name="parent_name" class="element text medium" type="text" maxlength="255"
                           value=""/>
                </div>
            </li>
            <li id="li_4">
                <label class="description" for="address">Address </label>
                <div>
                    <textarea id="address" name="address" class="element textarea medium" spellcheck="false"></textarea>
                </div>
            </li>
            <li id="li_3">
                <label class="description" for="class_id">Class</label>
                <div>
                    <select class="element select medium" id="class_id" name="class_id"/>
                    <?php
                    include_once '/Users/kiran.rao/Sites/School_project/src/Helper.php';
                    $classes = Helper::get_list('class', array('id', 'name'), 0, 0, '', '');
                    foreach ($classes as $class) {
                        print ("<option value = {$class['id']}>{$class['name']}</option>");
                    }
                    ?>
                    </select>
                </div>
            </li>
            <li id="li_4">
                <label class="description" for="section_id">Section</label>
                <div>
                    <select class="element select medium" id="section_id" name="section_id"/>
                    <?php

                    $sections = Helper::get_list('section', array('id', 'name'), 0, 0, '', '');
                    foreach ($sections as $section) {
                        print ("<option value = {$section['id']}>{$section['name']}</option>");
                    }
                    ?>
                    </select>
                </div>
            </li>

            <li class="buttons">
                <input type="hidden" name="form_id" value="119127"/>

                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit"/>
            </li>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>