<?php
require "/app/app/vendor/autoload.php";
use School\School;
$msg = '';
// Get school details from school id
if (isset($_GET['school_id'])) {
    $school = new School();
    $msg = $school->load_by_id('school', $_GET['school_id']);
}

// Update school entity
if (!empty($_POST)) {
    if ($_POST['Update'] == 'Update') {
        $school = new school();
        $school->id = $_POST['school_id'];
        $school->name = $_POST['school_name'];
        $school->phone = $_POST['phone'];
        $school->email = $_POST['email'];
        $school->website = $_POST['website'];
        $school->address = $_POST['address'];
        $msg = $school->update('school');
    }
    if ($_POST['Delete'] == 'Delete') {
        $school = new school();
        $school->id = $_POST['school_id'];
        $msg = $school->delete('school');
    }
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Create / Update School</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body">
<img id="top" src="top.png" alt="">
<div id="form_container">
    <h1><a>Create / Update School</a></h1>
    <?php
    if (!empty($msg)) {
        print("<div class='msg'>$msg</div>");
    }
    ?>
    <form id="school_form" class="appnitro" method="post" action="/School_project/src/edit_school.php?">
        <div class="form_description">
            <h2>Create / Update School</h2>
            <p>This is your form description. Click here to edit.</p>
        </div>

        <?php print("<input type='hidden' id='school_id' name='school_id'  class='element text medium' type='text' maxlength='255' value='{$school->id}'>"); ?>

        <ul>
            <li id="li_2">
                <label class="description" for="school_name">School Name*</label>
                <div>
                    <?php print("<input required id='school_name' name='school_name' class='element text medium' type='text' maxlength='255' value='{$school->name}'>"); ?>

                </div>
            </li>
            <li id="li_3">
                <label class="description" for="phone">Phone*</label>
                <div>
                    <?php print("<input required id='phone' type ='tel' pattern='^\d{10}$' name='phone' class='element text medium' type='text' maxlength='255' value='{$school->phone}'>"); ?>
                </div>
            </li>
            <li id="li_4">
                <label class="description" for="email">Email*</label>
                <div>
                    <?php print ("<input required id='email' name='email' class='element text medium' type='text' maxlength='255' value='{$school->email}'>"); ?>
                </div>
            </li>
            <li id="li_5">
                <label class="description" for="website">Web Site*</label>
                <div>
                    <?php print ("<input required id='website' name='website' class='element text medium' type='text' maxlength='255' value='{$school->website}'>"); ?>
                </div>
            </li>
            <li id="li_6">
                <label class="description" for="address">Address
                    <color
                    ='red'>*</color></label>
                <div>
                    <?php print("<input required id='address' name='address' class='element text medium' type='text' maxlength='255' value='{$school->address}'>"); ?>
                </div>
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="116952"/>
                <input id="saveForm" class="button_text" type="submit" name="Update" value="Update"/>
                <input id="saveForm" class="button_text" type="submit" name="Delete" value="Delete"/>
            </li>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>