<?php
require "/app/app/vendor/autoload.php";
use School\Section;
use School\Helper;
// Create a school entity
include_once '/Users/kiran.rao/Sites/School_project/src/Section.php';
include_once '/Users/kiran.rao/Sites/School_project/src/Helper.php';
$msg = '';
// Get school details from school id
if (isset($_GET['section_id'])) {
    $section = new Section();
    $msg = $section->load_by_id('section', $_GET['section_id']);
//        print_r($section);die();
}
if (!empty($_POST)) {
    if ($_POST['update'] == 'Update') {
        $section = new Section();
        $section->id = $_POST['section_id'];
        $section->name = $_POST['section_name'];
        $section->class_id = $_POST['class_id'];
        $msg = $section->update('section');
    }
    if ($_POST['delete'] == 'Delete') {
        $section = new Section();
        $section->id = $_POST['section_id'];
        $section->delete('section');
    }
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Edit / Update Section</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body">

<img id="top" src="top.png" alt="">
<div id="form_container">

    <h1><a>Create Class</a></h1>
    <?php
    if (!empty($msg)) {
        print("<div class='msg'>$msg</div>");
    }
    ?>
    <form id="form_119127" class="appnitro" method="post" action="">
        <div class="form_description">
            <h2>Update / Delete Section</h2>
            <!--            <p>This is your form description. Click here to edit.</p>-->
        </div>
        <?php print("<input hidden id='section_id' name='section_id' class='element text medium' type='text' maxlength='255' value='{$section->id}'>"); ?>
        <ul>
            <li id="li_2">
                <label class="description" for="element_2">Section Name </label>
                <div>
                    <?php
                    print ("<input id='section_name' name='section_name' class='element text medium' type='text' maxlength='255' value= '{$section->name}'>");
                    ?>
                </div>
            </li>
            <li id="li_3">
                <label class="description" for="class_id">Class </label>
                <div>
                    <select class="element select medium" id="class_id" name="class_id">
                        <?php
                        $classes = Helper::get_list('class', array('id', 'name'), 0, 0, '', '');
                        foreach ($classes as $class) {
                            if ($class['id'] == $section->class_id) {
                                print ("<option selected value = '{$class['id']}'>{$class['name']}</option>");
                            } else {
                                print ("<option value = '{$class['id']}'>{$class['name']}</option>");
                            }
                        }
                        ?>
                    </select>
                </div>
            </li>

            <li class="buttons">
                <input type="hidden" name="form_id" value="119127"/>
                <input id="update" class="button_text" type="submit" name="update" value="Update"/>
                <input id="saveForm" class="button_text" type="submit" name="delete" value="Delete"/>
            </li>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>