<?php
//print_r($_POST);die();
// Create a school entity
include_once '/Users/kiran.rao/Sites/School_project/src/School.php';
if (!empty($_POST)) {
    $school = new school();
    $school->name = $_POST['school_name'];
    $school->phone = $_POST['phone'];
    $school->email = $_POST['email'];
    $school->website = $_POST['website'];
    $school->address = $_POST['address'];
    $msg = $school->create();
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Create / Update School</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body">
<img id="top" src="top.png" alt="">
<div id="form_container">
    <h1><a>Create / Update School</a></h1>
    <!--    <div class='msg'>--><?php //echo $msg ? $msg : "" ?><!--</div>-->
    <form id="school_form" class="appnitro" method="post" action="/School_project/src/form_listener.php">
        <div class="form_description">
            <h2>Create / Update School</h2>
            <p>This is your form description. Click here to edit.</p>
        </div>
        <ul>
            <li id="li_6" class="">
                <label class="description" for="element_6">Select School </label>
                <div>
                    <select class="element select medium" id="select_school" name="select_school">
                        <?php
                        include_once '/Users/kiran.rao/Sites/School_project/src/Helper.php';
                        $schools = Helper::get_list('school', array('id', 'name'), 0, 0, '', '');
                        foreach ($schools as $school) {
                            echo "<option value = {$school['id']}>{$school['name']}</option>";
                        }
                        ?>
                    </select>
                </div>
                <p class="guidelines" id="guide_6"><small>Select school you want to edit</small></p>
            </li>
            <li id="li_1">
                <label class="description" for="school_name">School Name </label>
                <div>
                    <input id="school_name" name="school_name" class="element text medium" type="text" maxlength="255"
                           value=""/>
                </div>
            </li>
            <li id="li_2">
                <label class="description" for="phone">Phone </label>
                <div>
                    <input id="phone" name="phone" class="element text medium" type="text" maxlength="255" value=""/>
                </div>
            </li>
            <li id="li_3">
                <label class="description" for="email">Email </label>
                <div>
                    <input id="email" name="email" class="element text medium" type="text" maxlength="255" value=""/>
                </div>
            </li>
            <li id="li_4">
                <label class="description" for="website">Web Site </label>
                <div>
                    <input id="website" name="website" class="element text medium" type="text" maxlength="255"
                           value="http://"/>
                </div>
            </li>
            <li id="li_5">
                <label class="description" for="address">Address </label>
                <div>
                    <input id="address" name="address" class="element text medium" type="text" maxlength="255"
                           value=""/>
                </div>
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="116952"/>
                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit"/>
            </li>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>