<?php
require "/Users/kiran.rao/Sites/School_project/vendor/autoload.php";
use User\User;
ob_start();
session_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Untitled Form</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >

<img id="top" src="top.png" alt="">
<div id="form_container">

    <h1><a>Untitled Form</a></h1>
    <form id="form_122563" class="appnitro"  method="post" action="">
        <div class="form_description">
            <h2>Untitled Form</h2>
            <p>This is your form description. Click here to edit.</p>
        </div>
        <ul >

            <li id="li_1" >
                <label class="description" for="user_id">Login Id </label>
                <div>
                    <input id="user_id" name="user_id" class="element text medium" type="text" maxlength="255" value=""/>
                </div>
            </li>		<li id="li_2" >
                <label class="description" for="password">Password </label>
                <div>
                    <input id="password" type="password" name="password" class="element text medium" type="text" maxlength="255" value=""/>
                </div>
            </li>

            <li class="buttons">
                <input type="hidden" name="form_id" value="122563" />

                <input id="login" class="button_text" type="submit" name="submit" value="Submit" />
          </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">Form</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>
<?php
    if (!empty($_POST['user_id']) || !empty($_POST['password'])) {
       $login =  User::validate_login($_POST['user_id'], $_POST['password']);
    }
//    $user = User::validateLogin($_POST['user_id', 'password']);

?>