<?php
require "vendor/autoload.php";
use School\SchoolClass;
// Create a school entity
include_once '/Users/kiran.rao/Sites/School_project/src/SchoolClass.php';
if (!empty($_POST)) {
//    print_r($_POST);die();
    $class = new SchoolClass();
    $class->name = $_POST['class_name'];
    $class->school_id = $_POST['school_id'];
    $msg = $class->create('class');
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Untitled Form</title>
    <link rel="stylesheet" type="text/css" href="view.css" media="all">
    <script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body">

<img id="top" src="top.png" alt="">
<div id="form_container">

    <h1><a>Create Class</a></h1>
    <?php
    if (!empty($msg)) {
        print("<div class='msg'>$msg</div>");
    }
    ?>
    <form id="form_119127" class="appnitro" method="post" action="">
        <div class="form_description">
            <h2>Untitled Form</h2>
            <p>This is your form description. Click here to edit.</p>
        </div>
        <ul>

            <!--            <li id="li_1" >-->
            <!--                <label class="description" for="element_1">Class ID * </label>-->
            <!--                <div>-->
            <!--                    <input hidden id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/>-->
            <!--                </div>-->
            <!--            </li>		-->
            <li id="li_2">
                <label class="description" for="element_2">Class Name </label>
                <div>
                    <input id="class_name" name="class_name" class="element text medium" type="text" maxlength="255"
                           value=""/>
                </div>
            </li>
            <li id="li_3">
                <label class="description" for="school_id">School </label>
                <div>
                    <select class="element select medium" id="school_id" name="school_id" value= <?php ?>>
                        <?php
                        include_once '/Users/kiran.rao/Sites/School_project/src/Helper.php';
                        $schools = Helper::get_list('school', array('id', 'name'), 0, 0, '', '');
                        foreach ($schools as $school) {
                            print ("<option value = {$school['id']}>{$school['name']}</option>");
                        }
                        ?>
                    </select>
                </div>
            </li>

            <li class="buttons">
                <input type="hidden" name="form_id" value="119127"/>

                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit"/>
            </li>
        </ul>
    </form>
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>
<img id="bottom" src="bottom.png" alt="">
</body>
</html>